version: "{build}"

environment:
  nodejs_version: "5.3.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run clean
  - npm run build
  - npm run release

build: off
